development:
  port: 5432
  adapter: postgresql
  encoding: unicode
  database: <%= ENV.fetch("DATABASE_DATABASE") { "dario-bot" } %>
  pool: 5
  username: <%= ENV.fetch("DATABASE_USERNAME") { "dario-bot" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "dario-bot" } %>
  host: <%= ENV.fetch("DATABASE_HOST") { "localhost-bot" } %>